import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';
const API='http://localhost:5000/api';
function App(){const[events,setEvents]=useState([]),[regs,setRegs]=useState([]),[page,setPage]=useState('home'),[query,setQuery]=useState(''),[cat,setCat]=useState('All'),[selected,setSelected]=useState(null),[admin,setAdmin]=useState(false);const empty={name:'',category:'Coding',date:'',time:'',venue:'',description:''};const[form,setForm]=useState(empty);const[reg,setReg]=useState({name:'',email:'',collegeYear:'',phone:''});
const load=()=>{fetch(API+'/events').then(r=>r.json()).then(setEvents);fetch(API+'/registrations').then(r=>r.json()).then(setRegs)};useEffect(load,[]);
const filtered=events.filter(e=>(e.name.toLowerCase().includes(query.toLowerCase())||e.description.toLowerCase().includes(query.toLowerCase()))&&(cat==='All'||e.category===cat));
const save=async e=>{e.preventDefault();await fetch(API+'/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});setForm(empty);load()};
const update=async e=>{e.preventDefault();await fetch(API+'/events/'+form.id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});setForm(empty);load()};
const remove=async id=>{await fetch(API+'/events/'+id,{method:'DELETE'});load()};
const submitReg=async e=>{e.preventDefault();await fetch(API+'/registrations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...reg,eventId:selected.id,eventName:selected.name})});alert('Registration submitted!');setReg({name:'',email:'',collegeYear:'',phone:''});setSelected(null);load()};
return <><header><div className="brand">⚡ CodeChef <span>ABESEC</span></div><nav><button onClick={()=>setPage('home')}>Home</button><button onClick={()=>setPage('events')}>Events</button><button className="adminBtn" onClick={()=>setAdmin(!admin)}>{admin?'Student View':'Admin'}</button></nav></header>
{admin?<Admin events={events} regs={regs} form={form} setForm={setForm} save={save} update={update} remove={remove}/>:<><section className="hero"><div><p className="eyebrow">CODECHEF ABESEC CHAPTER</p><h1>Build. Compete.<br/><em>Grow Together.</em></h1><p>Discover coding contests, workshops and hackathons happening at your campus.</p><button className="primary" onClick={()=>setPage('events')}>Explore Events →</button></div><div className="heroCard"><div className="orb">💻</div><h3>Next up</h3><strong>{events[0]?.name}</strong><small>{events[0]?.date} · {events[0]?.venue}</small></div></section>
<section className="section"><div className="sectionHead"><div><p className="eyebrow">WHAT'S HAPPENING</p><h2>{page==='home'?'Upcoming Events':'All Events'}</h2></div>{page==='home'&&<button className="link" onClick={()=>setPage('events')}>View all →</button>}</div>{page==='events'&&<div className="filters"><input placeholder="Search events..." value={query} onChange={e=>setQuery(e.target.value)}/><select value={cat} onChange={e=>setCat(e.target.value)}><option>All</option><option>Coding</option><option>Workshop</option><option>Hackathon</option><option>Talk</option></select></div>}<div className="grid">{(page==='home'?events.slice(0,3):filtered).map(e=><article className="event" key={e.id}><div className="tag">{e.category}</div><h3>{e.name}</h3><p>{e.description}</p><div className="meta">📅 {e.date} · {e.time}<br/>📍 {e.venue}</div><button className="primary full" onClick={()=>setSelected(e)}>Register →</button></article>)}</div></section>{selected&&<div className="modal"><form onSubmit={submitReg}><button type="button" className="close" onClick={()=>setSelected(null)}>×</button><p className="eyebrow">REGISTRATION</p><h2>{selected.name}</h2><input required placeholder="Name" value={reg.name} onChange={e=>setReg({...reg,name:e.target.value})}/><input required type="email" placeholder="Email" value={reg.email} onChange={e=>setReg({...reg,email:e.target.value})}/><input required placeholder="College / Year" value={reg.collegeYear} onChange={e=>setReg({...reg,collegeYear:e.target.value})}/><input required placeholder="Phone number" value={reg.phone} onChange={e=>setReg({...reg,phone:e.target.value})}/><button className="primary full">Submit Registration</button></form></div>}</>}
<footer>© 2026 CodeChef ABESEC Chapter · Explore. Collaborate. Create.</footer></>}
function Admin({events,regs,form,setForm,save,update,remove}){const[editing,setEditing]=useState(false);return <main className="admin"><div className="sectionHead"><div><p className="eyebrow">CONTROL ROOM</p><h2>Admin Dashboard</h2></div></div><div className="adminGrid"><form className="panel" onSubmit={editing?update:save}><h3>{editing?'Edit Event':'Add Event'}</h3>{['name','date','time','venue','description'].map(k=><input key={k} required placeholder={k[0].toUpperCase()+k.slice(1)} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Coding</option><option>Workshop</option><option>Hackathon</option><option>Talk</option></select><button className="primary full">{editing?'Update':'Add'} Event</button>{editing&&<button type="button" className="secondary full" onClick={()=>{setEditing(false);setForm({name:'',category:'Coding',date:'',time:'',venue:'',description:''})}}>Cancel</button>}</form><div className="panel"><h3>Events</h3>{events.map(e=><div className="adminRow" key={e.id}><div><b>{e.name}</b><small>{e.date} · {e.category}</small></div><div><button onClick={()=>{setEditing(true);setForm(e)}}>Edit</button><button onClick={()=>remove(e.id)}>Delete</button></div></div>)}</div></div><div className="panel registrations"><h3>Registered Students ({regs.length})</h3>{regs.length?<table><thead><tr><th>Name</th><th>Email</th><th>Event</th><th>College/Year</th><th>Phone</th></tr></thead><tbody>{regs.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.email}</td><td>{r.eventName}</td><td>{r.collegeYear}</td><td>{r.phone}</td></tr>)}</tbody></table>:<p>No registrations yet.</p>}</div></main>}
createRoot(document.getElementById('root')).render(<App/>);
